version: 2.1.0.{build}
image: Visual Studio 2017

configuration:
  - Release
environment:
  PROJECT: SqlBulkUpsert
  COVERALLS_REPO_TOKEN:
    secure: BZtcZR6WzervWOhyop4GC7pKy4lVKug2S0J6IVgmWv0ylXTsup23yLD54HPz53Ua
  COVERALLS_SERVICE_NAME: appveyor
  COVERALLS_SERVICE_JOB_ID: '%APPVEYOR_JOB_ID%'
  SqlBulkUpsertTestConnectionString: Server=(local)\SQL2014;Database=SqlBulkUpsertTestDb;User ID=sa;Password=Password12!
cache:
  - packages -> **\packages.config
notifications:
  - provider: Slack
    incoming_webhook:
      secure: c7l1UmXHWpIDLL1awU4r0QYVPToYM/XjV8trFyD1oHArKxs/vBTYiKYScr1EhCUgmEX6sAFBTvkUHF/k5B+cGjzqRBR2XkAO+lzk8cHQ1FI=
services:
  - mssql2014

before_build:
  - appveyor-retry nuget restore -DisableParallelProcessing
build:
  project: $(PROJECT).sln
  verbosity: minimal

test_script:
  - ps: |
      & "$env:PROJECT.Tests\Attach-Database.ps1" -Instance '(local)\SQL2014'
      .\Test-Project.ps1 -Assembly SqlBulkUpsert
after_test:
  - ps: .\Submit-CodeCoverageResults.ps1

deploy_script:
  - ps: .\Deploy-Project.ps1