version: 2.1.0.{build}
image: Visual Studio 2017

configuration:
  - Release
environment:
  PROJECT: SqlBulkUpsert
  SqlBulkUpsertTestConnectionString: Server=(local)\SQL2014;Database=SqlBulkUpsertTestDb;User ID=sa;Password=Password12!
cache:
  - packages -> **\packages.config
notifications:
  - provider: Slack
    incoming_webhook:
      secure: c7l1UmXHWpIDLL1awU4r0QYVPToYM/XjV8trFyD1oHArKxs/vBTYiKYScr1EhCUgmEX6sAFBTvkUHF/k5B+cGjzqRBR2XkAO+lzk8cHQ1FI=
services:
  - mssql2014

before_build:
  - appveyor-retry nuget restore -DisableParallelProcessing
build:
  project: $(PROJECT).sln
  verbosity: minimal

test_script:
  - ps: & "$env:PROJECT.Test\Attach-Database.ps1" -Instance '(local)\SQL2014'
  - vstest.console /logger:Appveyor "%PROJECT%.Test\bin\%CONFIGURATION%\%PROJECT%.Test.dll"

deploy_script:
  - ps: .\Deploy-Project.ps1